import type { Migration } from "../migration-runner";

export const userImportPreviewsMigration: Migration = {
  id: "0005_user_import_previews",
  statements: [
    `CREATE TABLE user_import_previews (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      owner_user_id BIGINT UNSIGNED NOT NULL,
      academic_year_id BIGINT UNSIGNED NOT NULL,
      mode VARCHAR(20) NOT NULL DEFAULT 'CREATE_ONLY',
      source_sha256 BINARY(32) NOT NULL,
      commit_token_hash BINARY(32) NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
      total_rows INT UNSIGNED NOT NULL,
      create_count INT UNSIGNED NOT NULL DEFAULT 0,
      update_count INT UNSIGNED NOT NULL DEFAULT 0,
      unchanged_count INT UNSIGNED NOT NULL DEFAULT 0,
      duplicate_count INT UNSIGNED NOT NULL DEFAULT 0,
      error_count INT UNSIGNED NOT NULL DEFAULT 0,
      blocking_count INT UNSIGNED NOT NULL DEFAULT 0,
      expires_at DATETIME(6) NOT NULL,
      committed_at DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      CONSTRAINT pk_user_import_previews PRIMARY KEY (id),
      CONSTRAINT uq_user_import_previews_token UNIQUE (commit_token_hash),
      CONSTRAINT fk_user_import_previews_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT fk_user_import_previews_year FOREIGN KEY (academic_year_id) REFERENCES academic_years (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_user_import_previews_mode CHECK (mode IN ('CREATE_ONLY')),
      CONSTRAINT chk_user_import_previews_status CHECK (status IN ('PENDING', 'COMMITTING', 'COMMITTED', 'EXPIRED', 'FAILED')),
      CONSTRAINT chk_user_import_previews_counts CHECK (blocking_count <= total_rows),
      INDEX idx_user_import_previews_owner_status_expiry (owner_user_id, status, expires_at),
      INDEX idx_user_import_previews_expiry (expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE user_import_preview_rows (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      preview_id BIGINT UNSIGNED NOT NULL,
      \`row_number\` INT UNSIGNED NOT NULL,
      username VARCHAR(100) NULL,
      display_name VARCHAR(200) NULL,
      class_code VARCHAR(50) NULL,
      class_id BIGINT UNSIGNED NULL,
      existing_user_id BIGINT UNSIGNED NULL,
      classification VARCHAR(20) NOT NULL,
      blocking BOOLEAN NOT NULL DEFAULT FALSE,
      error_json JSON NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      CONSTRAINT pk_user_import_preview_rows PRIMARY KEY (id),
      CONSTRAINT uq_user_import_preview_rows_number UNIQUE (preview_id, \`row_number\`),
      CONSTRAINT fk_user_import_preview_rows_preview FOREIGN KEY (preview_id) REFERENCES user_import_previews (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT fk_user_import_preview_rows_class FOREIGN KEY (class_id) REFERENCES classes (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT fk_user_import_preview_rows_user FOREIGN KEY (existing_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_user_import_preview_rows_classification CHECK (classification IN ('CREATE', 'UNCHANGED', 'WOULD_UPDATE', 'DUPLICATE', 'ERROR')),
      CONSTRAINT chk_user_import_preview_rows_number CHECK (\`row_number\` > 0),
      INDEX idx_user_import_preview_rows_filter (preview_id, classification, blocking, \`row_number\`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
