import type { Migration } from "../migration-runner";

/** Machine clients, credentials, explicit grants, and replay protection. */
export const integrationsMigration: Migration = {
  id: "0018_integrations",
  statements: [
    `CREATE TABLE integration_clients (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      name VARCHAR(120) NOT NULL,
      platform_hint VARCHAR(32) NOT NULL,
      owner_user_id BIGINT UNSIGNED NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
      description VARCHAR(500) NULL,
      policy_version INT UNSIGNED NOT NULL DEFAULT 1,
      created_by_user_id BIGINT UNSIGNED NOT NULL,
      last_used_at DATETIME(6) NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      CONSTRAINT pk_integration_clients PRIMARY KEY (id),
      CONSTRAINT fk_integration_clients_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT fk_integration_clients_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_integration_clients_status CHECK (status IN ('ACTIVE', 'DISABLED')),
      CONSTRAINT chk_integration_clients_name CHECK (CHAR_LENGTH(TRIM(name)) BETWEEN 1 AND 120),
      CONSTRAINT chk_integration_clients_platform CHECK (CHAR_LENGTH(TRIM(platform_hint)) BETWEEN 1 AND 32),
      CONSTRAINT chk_integration_clients_policy_version CHECK (policy_version > 0),
      INDEX idx_integration_clients_owner_status (owner_user_id, status, id),
      INDEX idx_integration_clients_status_last_used (status, last_used_at, id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE integration_credentials (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      integration_client_id BIGINT UNSIGNED NOT NULL,
      token_prefix VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      token_digest BINARY(32) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
      valid_from DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      expires_at DATETIME(6) NULL,
      last_used_at DATETIME(6) NULL,
      revoked_at DATETIME(6) NULL,
      revoked_by_user_id BIGINT UNSIGNED NULL,
      revoke_reason VARCHAR(500) NULL,
      rotation_parent_id BIGINT UNSIGNED NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      CONSTRAINT pk_integration_credentials PRIMARY KEY (id),
      CONSTRAINT uq_integration_credentials_prefix UNIQUE (token_prefix),
      CONSTRAINT uq_integration_credentials_digest UNIQUE (token_digest),
      CONSTRAINT fk_integration_credentials_client FOREIGN KEY (integration_client_id) REFERENCES integration_clients (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT fk_integration_credentials_revoker FOREIGN KEY (revoked_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT fk_integration_credentials_parent FOREIGN KEY (rotation_parent_id) REFERENCES integration_credentials (id) ON DELETE SET NULL ON UPDATE RESTRICT,
      CONSTRAINT chk_integration_credentials_status CHECK (status IN ('ACTIVE', 'REVOKED')),
      CONSTRAINT chk_integration_credentials_expiry CHECK (expires_at IS NULL OR expires_at > valid_from),
      CONSTRAINT chk_integration_credentials_revoke CHECK ((status = 'ACTIVE' AND revoked_at IS NULL AND revoked_by_user_id IS NULL) OR (status = 'REVOKED' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL)),
      INDEX idx_integration_credentials_client_status_expiry (integration_client_id, status, expires_at),
      INDEX idx_integration_credentials_expiry (status, expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE integration_grants (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      integration_client_id BIGINT UNSIGNED NOT NULL,
      capability VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      scope_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      scope_ids_json JSON NOT NULL,
      constraints_json JSON NOT NULL,
      grant_version INT UNSIGNED NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
      valid_from DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      expires_at DATETIME(6) NULL,
      issued_by_user_id BIGINT UNSIGNED NOT NULL,
      revoked_at DATETIME(6) NULL,
      revoked_by_user_id BIGINT UNSIGNED NULL,
      revoke_reason VARCHAR(500) NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      CONSTRAINT pk_integration_grants PRIMARY KEY (id),
      CONSTRAINT fk_integration_grants_client FOREIGN KEY (integration_client_id) REFERENCES integration_clients (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT fk_integration_grants_issuer FOREIGN KEY (issued_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT fk_integration_grants_revoker FOREIGN KEY (revoked_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_integration_grants_status CHECK (status IN ('ACTIVE', 'REVOKED')),
      CONSTRAINT chk_integration_grants_version CHECK (grant_version > 0),
      CONSTRAINT chk_integration_grants_expiry CHECK (expires_at IS NULL OR expires_at > valid_from),
      CONSTRAINT chk_integration_grants_revoke CHECK ((status = 'ACTIVE' AND revoked_at IS NULL AND revoked_by_user_id IS NULL) OR (status = 'REVOKED' AND revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL)),
      INDEX idx_integration_grants_client_capability (integration_client_id, capability, status, expires_at),
      INDEX idx_integration_grants_client_version (integration_client_id, grant_version),
      INDEX idx_integration_grants_scope_lookup (scope_type, status, expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE integration_idempotency_keys (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      integration_client_id BIGINT UNSIGNED NOT NULL,
      idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      request_hash BINARY(32) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'PROCESSING',
      response_json JSON NULL,
      expires_at DATETIME(6) NOT NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      completed_at DATETIME(6) NULL,
      CONSTRAINT pk_integration_idempotency_keys PRIMARY KEY (id),
      CONSTRAINT uq_integration_idempotency_client_key UNIQUE (integration_client_id, idempotency_key),
      CONSTRAINT fk_integration_idempotency_client FOREIGN KEY (integration_client_id) REFERENCES integration_clients (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT chk_integration_idempotency_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
      INDEX idx_integration_idempotency_expiry (expires_at, status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
