import type { Migration } from "../migration-runner";

/** Durable prepare/confirm state for agent operations requiring approval. */
export const agentActionsMigration: Migration = {
  id: "0020_agent_actions",
  statements: [
    `CREATE TABLE agent_action_requests (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      integration_client_id BIGINT UNSIGNED NOT NULL,
      owner_user_id BIGINT UNSIGNED NOT NULL,
      capability VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      operation VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      target_type VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      target_id BIGINT UNSIGNED NOT NULL,
      normalized_plan JSON NOT NULL,
      plan_hash BINARY(32) NOT NULL,
      risk_level VARCHAR(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      expected_versions_json JSON NOT NULL,
      grant_version INT UNSIGNED NOT NULL,
      status VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'AWAITING_CONFIRMATION',
      approval_method VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'AGENT_CONFIRM',
      expires_at DATETIME(6) NOT NULL,
      result_json JSON NULL,
      error_code VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NULL,
      created_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      updated_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      executed_at DATETIME(6) NULL,
      CONSTRAINT pk_agent_action_requests PRIMARY KEY (id),
      CONSTRAINT fk_agent_action_requests_client FOREIGN KEY (integration_client_id) REFERENCES integration_clients (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT fk_agent_action_requests_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_agent_action_requests_plan CHECK (JSON_VALID(normalized_plan)),
      CONSTRAINT chk_agent_action_requests_versions CHECK (JSON_VALID(expected_versions_json)),
      CONSTRAINT chk_agent_action_requests_risk CHECK (risk_level IN ('R0', 'R1', 'R2', 'R3', 'R4')),
      CONSTRAINT chk_agent_action_requests_status CHECK (status IN ('AWAITING_CONFIRMATION', 'AWAITING_APPROVAL', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'REJECTED', 'CANCELLED', 'EXPIRED')),
      CONSTRAINT chk_agent_action_requests_approval CHECK (approval_method IN ('NONE', 'AGENT_CONFIRM', 'WEB_APPROVAL')),
      CONSTRAINT chk_agent_action_requests_expiry CHECK (expires_at > created_at),
      INDEX idx_agent_action_requests_client_created (integration_client_id, created_at, id),
      INDEX idx_agent_action_requests_status_expiry (status, expires_at, id),
      INDEX idx_agent_action_requests_owner_created (owner_user_id, created_at, id),
      INDEX idx_agent_action_requests_target (target_type, target_id, created_at, id),
      INDEX idx_agent_action_requests_plan_hash (plan_hash)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE agent_action_approvals (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      action_request_id BIGINT UNSIGNED NOT NULL,
      approved_by_user_id BIGINT UNSIGNED NULL,
      approval_source VARCHAR(30) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      plan_hash BINARY(32) NOT NULL,
      outcome VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
      reason VARCHAR(500) NULL,
      approved_at DATETIME(6) NOT NULL DEFAULT UTC_TIMESTAMP(6),
      consumed_at DATETIME(6) NULL,
      CONSTRAINT pk_agent_action_approvals PRIMARY KEY (id),
      CONSTRAINT fk_agent_action_approvals_action FOREIGN KEY (action_request_id) REFERENCES agent_action_requests (id) ON DELETE CASCADE ON UPDATE RESTRICT,
      CONSTRAINT fk_agent_action_approvals_user FOREIGN KEY (approved_by_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
      CONSTRAINT chk_agent_action_approvals_source CHECK (approval_source IN ('WEB', 'AGENT_CONFIRM')),
      CONSTRAINT chk_agent_action_approvals_outcome CHECK (outcome IN ('APPROVED', 'REJECTED', 'FAILED')),
      INDEX idx_agent_action_approvals_action_outcome (action_request_id, outcome, approved_at),
      INDEX idx_agent_action_approvals_user_created (approved_by_user_id, approved_at, id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  ],
};
