<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { HttpStaffApi } from "../features/staff/api";
import type { MonitorPage, MonitorSession } from "../features/staff/types";
import { formatDate, messageFrom } from "../features/staff/helpers";
import { useStaffAuth } from "../features/staff/auth-store";

const api = new HttpStaffApi();
const auth = useStaffAuth();
const route = useRoute();
const scheduleId = computed(() => String(route.query.scheduleId ?? ""));
const data = ref<MonitorPage | null>(null);
const selected = ref<MonitorSession | null>(null);
const search = ref("");
const loading = ref(true);
const paused = ref(false);
const stale = ref(false);
const error = ref("");
const lastUpdated = ref<Date | null>(null);
const minutes = ref("");
const reason = ref("");
const operation = ref<"extend" | "end" | "reset" | null>(null);
const isAdmin = computed(() => auth.user.value?.role === "ADMIN");
let timer: number | undefined;
let visibilityHandler: (() => void) | undefined;

const ageLabel = computed(() => { if (!lastUpdated.value) return "Belum diperbarui"; const seconds = Math.max(0, Math.round((Date.now() - lastUpdated.value.getTime()) / 1000)); return `Diperbarui ${seconds} detik lalu`; });
async function load(): Promise<void> { if (!scheduleId.value) { loading.value = false; error.value = "Pilih schedule dari halaman monitoring."; return; } loading.value = true; try { data.value = await api.monitor(scheduleId.value, undefined, search.value); lastUpdated.value = new Date(); stale.value = false; } catch (cause) { stale.value = true; error.value = messageFrom(cause, "Data monitoring belum tersedia."); } finally { loading.value = false; scheduleNext(); } }
function scheduleNext(): void { if (timer !== undefined) window.clearTimeout(timer); if (paused.value || document.visibilityState === "hidden") return; timer = window.setTimeout(() => { void load(); }, 12_000 + Math.round(Math.random() * 6_000)); }
function togglePause(): void { paused.value = !paused.value; if (paused.value && timer !== undefined) window.clearTimeout(timer); else void load(); }
function onVisibility(): void { if (document.visibilityState === "visible" && !paused.value) void load(); else if (timer !== undefined) window.clearTimeout(timer); }
function open(session: MonitorSession): void { selected.value = session; operation.value = null; reason.value = ""; minutes.value = ""; }
function closeDrawer(): void { selected.value = null; operation.value = null; }
async function submitOperation(): Promise<void> { if (!selected.value || !reason.value.trim()) return; try { if (operation.value === "extend") await api.extendSession(selected.value.id, Number(minutes.value), reason.value, selected.value.version); if (operation.value === "end") await api.endSession(selected.value.id, reason.value, selected.value.version); if (operation.value === "reset") await api.resetAttempt(selected.value.id, reason.value); closeDrawer(); await load(); } catch (cause) { error.value = messageFrom(cause); } }
async function closeSchedule(): Promise<void> { if (!scheduleId.value || !window.confirm("Tutup jadwal? Session aktif akan difinalisasi sebagai jadwal ditutup.")) return; try { const schedule = (await api.schedules()).items.find((item) => item.id === scheduleId.value); if (!schedule) throw new Error("schedule missing"); await api.transitionSchedule(schedule.id, "close", schedule.updatedAt, "Ditutup dari halaman monitoring"); await load(); } catch (cause) { error.value = messageFrom(cause, "Jadwal belum dapat ditutup."); } }
onMounted(() => { visibilityHandler = onVisibility; document.addEventListener("visibilitychange", visibilityHandler); void load(); });
onBeforeUnmount(() => { if (timer !== undefined) window.clearTimeout(timer); if (visibilityHandler) document.removeEventListener("visibilitychange", visibilityHandler); });
</script>

<template>
  <header class="page-heading between"><div><p class="eyebrow">Guru · Reliability</p><h1>Monitoring ujian</h1><p class="muted">Schedule {{ scheduleId || "—" }} · daftar session dipaginasi server.</p></div><div class="monitor-actions"><button class="btn-secondary" type="button" @click="togglePause">{{ paused ? 'Lanjutkan polling' : 'Pause polling' }}</button><button class="btn-secondary" type="button" @click="load">Segarkan</button><button class="btn-danger" type="button" :disabled="!scheduleId" @click="closeSchedule">Tutup jadwal</button></div></header>
  <div class="monitor-meta"><span :class="{ stale }" class="age-indicator">{{ stale ? 'Data mungkin sudah usang' : ageLabel }}</span><span v-if="paused" class="badge">Polling dipause</span><span v-if="error" class="muted">{{ error }}</span></div>
  <section v-if="data" class="stat-grid" aria-label="Ringkasan peserta"><article class="card stat-card"><span>Target</span><strong>{{ data.counts.target }}</strong></article><article class="card stat-card"><span>Belum mulai</span><strong>{{ data.counts.notStarted }}</strong></article><article class="card stat-card"><span>Aktif</span><strong>{{ data.counts.active }}</strong></article><article class="card stat-card"><span>Submitted</span><strong>{{ data.counts.submitted }}</strong></article><article class="card stat-card"><span>Expired</span><strong>{{ data.counts.expired }}</strong></article></section>
  <section class="card table-card"><div class="table-toolbar"><h2>Session</h2><form class="search-form" @submit.prevent="load"><label class="sr-only" for="monitor-search">Cari peserta</label><input id="monitor-search" v-model="search" placeholder="Cari peserta" /><button class="btn-secondary" type="submit">Cari</button></form></div><div v-if="loading" class="table-state">Memuat monitoring…</div><div v-else-if="!data || data.sessions.items.length === 0" class="table-state"><strong>Belum ada session</strong><span class="muted">Session peserta akan tampil setelah ujian dimulai.</span></div><div v-else class="table-scroll"><table><caption class="sr-only">Daftar session ujian</caption><thead><tr><th>Peserta</th><th>Status</th><th>Progress</th><th>Deadline</th><th>Last activity</th></tr></thead><tbody><tr v-for="session in data.sessions.items" :key="session.id" tabindex="0" @click="open(session)" @keydown.enter="open(session)"><td><strong>{{ session.participantName }}</strong><small>{{ session.username ?? 'Latihan' }} · attempt {{ session.attemptNo }}</small></td><td><span class="badge" :class="session.status === 'ACTIVE' ? 'badge-active' : ''">{{ session.status }}</span></td><td>{{ session.answeredCount }}/{{ session.questionCount }}</td><td>{{ formatDate(session.deadlineAt) }}</td><td>{{ formatDate(session.lastSeenAt) }}</td></tr></tbody></table></div></section>
  <div v-if="selected" class="overlay" role="dialog" aria-modal="true" aria-labelledby="session-drawer-title"><aside class="drawer"><div class="between"><div><p class="eyebrow">Session {{ selected.id }}</p><h2 id="session-drawer-title">{{ selected.participantName }}</h2></div><button class="btn-quiet" type="button" @click="closeDrawer">Tutup</button></div><dl class="detail-list"><div><dt>Status</dt><dd>{{ selected.status }}</dd></div><div><dt>Attempt</dt><dd>{{ selected.attemptNo }}</dd></div><div><dt>Progress</dt><dd>{{ selected.answeredCount }}/{{ selected.questionCount }} terjawab</dd></div><div><dt>Deadline</dt><dd>{{ formatDate(selected.deadlineAt) }}</dd></div><div><dt>Aktivitas terakhir</dt><dd>{{ formatDate(selected.lastSeenAt) }}</dd></div></dl><p class="muted small-copy">Detail tidak memuat raw answer, answer key, cookie, atau fingerprint perangkat.</p><div v-if="selected.status === 'ACTIVE'" class="drawer-actions"><button class="btn-secondary" type="button" @click="operation = 'extend'">Perpanjang waktu</button><button class="btn-danger" type="button" @click="operation = 'end'">Akhiri sesi</button><button v-if="isAdmin" class="btn-secondary" type="button" @click="operation = 'reset'">Reset attempt</button></div><form v-if="operation" class="operation-form" @submit.prevent="submitOperation"><h3>{{ operation === 'extend' ? 'Perpanjang waktu' : operation === 'end' ? 'Akhiri sesi' : 'Reset attempt' }}</h3><label v-if="operation === 'extend'">Menit<input v-model.number="minutes" type="number" min="1" max="180" required /></label><label>Alasan wajib<textarea v-model="reason" maxlength="500" rows="3" required /></label><div class="drawer-actions"><button class="btn-secondary" type="button" @click="operation = null">Batal</button><button class="btn-primary" type="submit">Konfirmasi</button></div></form></aside></div>
</template>

<style scoped>
.page-heading { align-items: flex-start; margin-bottom: 12px; }.page-heading h1 { margin: 0 0 6px; }.eyebrow { margin: 0 0 4px; color: var(--primary); font-weight: 700; }.monitor-actions { display: flex; flex-wrap: wrap; gap: 8px; }.monitor-meta { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; margin-bottom: 14px; }.age-indicator { color: var(--muted); font-size: .9rem; }.age-indicator.stale { color: var(--warning); font-weight: 700; }.stat-grid { display: grid; grid-template-columns: repeat(5, minmax(120px, 1fr)); gap: 10px; margin-bottom: 14px; }.stat-card { display: grid; gap: 4px; padding: 14px; }.stat-card strong { font-size: 1.6rem; }.table-card { padding: 20px; }.table-toolbar { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin-bottom: 12px; }.table-toolbar h2 { margin: 0; }.search-form { display: flex; gap: 8px; }.search-form input { min-height: 40px; min-width: min(280px, 45vw); }.table-scroll { overflow-x: auto; } table { width: 100%; border-collapse: collapse; } th, td { padding: 12px 10px; text-align: left; border-bottom: 1px solid var(--border); } tr[tabindex] { cursor: pointer; } tr[tabindex]:hover { background: var(--primary-soft); } th { color: var(--muted); font-size: .8rem; } td small { display: block; color: var(--subtle); margin-top: 3px; }.table-state { display: grid; place-items: center; gap: 6px; min-height: 180px; }.badge { display: inline-flex; padding: 4px 8px; border-radius: 99px; color: var(--primary); background: var(--primary-soft); font-size: .78rem; font-weight: 700; }.badge-active { color: var(--success); background: var(--success-soft); }.overlay { position: fixed; inset: 0; z-index: 20; display: flex; justify-content: flex-end; background: rgb(2 6 23 / 45%); }.drawer { width: min(480px, 100%); height: 100%; overflow: auto; padding: 24px; background: var(--surface); }.detail-list { display: grid; gap: 12px; }.detail-list dt { color: var(--subtle); font-size: .82rem; }.detail-list dd { margin: 3px 0 0; }.drawer-actions { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 18px; }.operation-form { margin-top: 20px; padding-top: 18px; border-top: 1px solid var(--border); }.operation-form label { display: grid; gap: 6px; margin: 12px 0; font-weight: 600; }.operation-form input, .operation-form textarea { min-height: 40px; border: 1px solid var(--border-strong); border-radius: 8px; padding: 8px; color: var(--text); background: var(--surface); font-weight: 400; }.small-copy { font-size: .84rem; }.sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0; }
@media (max-width: 700px) { .page-heading, .table-toolbar { display: grid; }.stat-grid { grid-template-columns: repeat(2, 1fr); }.search-form input { min-width: 0; flex: 1; }.drawer { padding: 18px 14px; } }
</style>
